[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  GA_PROPERTY_ID = "333133275"
  META_ADS_ACCOUNT_ID = "act_23302665"

[context.deploy-preview.environment]
  GA_PROPERTY_ID = "333133275"

[context.branch-deploy.environment]
  GA_PROPERTY_ID = "333133275"

# Add function dependencies
[[plugins]]
  package = "@netlify/plugin-functions-core"

# Specific function configuration
[[plugins]]
  package = "netlify-plugin-inline-functions-env"
